### ISSUE TITLE
undefined method `key?' for #<ActiveRecord::Relation []>

### ISSUE THREAD

**Issue by mooreniemi** [carlesjove/collection_json_rails#6]
def index
    @books = Book.all
    respond_to do |format|
      format.html
      format.json {render json: @books, status: :ok}
    end

error at format.json

**Comment by carlesjove** [comment]
Oops! I'll check it out and let you know when I have a fix. Sorry for that.

**Comment by carlesjove** [comment]
Commenting here for documentation:

The problem here is that since `ActiveRecord::Relation` returns an empty `Array` (as expected), [`serialize`](https://github.com/carlesjove/collection_json_rails/blob/master/lib/collection_json_rails/action_controller/render.rb#L23) can't infer the name of the `CJ::Serializer`, and thus [`is_collection_json?`](https://github.com/carlesjove/collection_json_rails/blob/master/lib/collection_json_rails/action_controller/render.rb#L49) raises an error.

A quick fix would be to simply return an empty `Array`, just like Rails does by default, but it'd be more appropiate to get a CJ response with no `items`.

**Comment by carlesjove** [comment]
@mooreniemi Just released version 0.4.1 as a quick fix, which will return an empty array, which is the default Rails behaviour. I need some time to figure out how to respond with a CJ representation with no `items`.

If it is critical for you to get a CJ response even when there are no items (i.e. because you want a `template` in the response), you can still [build the collection manually](https://github.com/carlesjove/cj-rails-6/commit/d4adf89f1144f038ee6b3c63c92e9e7d31ec6475). 

Sorry for the inconvenience.

**Comment by carlesjove** [comment]
@mooreniemi Fixed :-)
